/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Team } from "./team";
import { Expose, Type } from "class-transformer";

export class Bucket extends SpeakeasyBase {
    /**
     * Bucket auth token if set, otherwise this value is null.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "auth_token" })
    authToken?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "collections_url" })
    collectionsUrl?: string;

    /**
     * True if this bucket is the 'default' for a team. Default buckets cannot be deleted.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "default" })
    default?: boolean;

    /**
     * The unique identifier used to address a bucket.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "key" })
    key?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "messages_url" })
    messagesUrl?: string;

    /**
     * The name of this bucket as displayed in your dashboard.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "team" })
    @Type(() => Team)
    team?: Team;

    @SpeakeasyMetadata()
    @Expose({ name: "tests_url" })
    testsUrl?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "trigger_url" })
    triggerUrl?: string;

    /**
     * True if this bucket is configured to verify ssl for requests made to it.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "verify_ssl" })
    verifySsl?: boolean;
}
