/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

/**
 * The changes in average response time compared to the last period.
 */
export class MetricsChangesFromLastPeriod extends SpeakeasyBase {}

export class MetricsResponseTimes extends SpeakeasyBase {
    /**
     * The average response time in miliseconds for all the requests for this test in this time interval.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "avg_response_time_ms" })
    avgResponseTimeMs?: number;

    /**
     * 1 if there's a successful request in this time interval, or 0 if there isn't.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "success_ratio" })
    successRatio?: number;

    /**
     * The timestamp in Unix format for the specified timeframe.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "timestamp" })
    timestamp?: number;
}

/**
 * The average response time for different percentiles for the request in the requested timeframe.
 */
export class MetricsThisTimePeriod extends SpeakeasyBase {}

export class Metrics extends SpeakeasyBase {
    /**
     * The changes in average response time compared to the last period.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "changes_from_last_period" })
    @Type(() => MetricsChangesFromLastPeriod)
    changesFromLastPeriod?: MetricsChangesFromLastPeriod;

    /**
     * The environment_uuid that filters this request.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "environment_uuid" })
    environmentUuid?: string;

    /**
     * The region that filters this request.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "region" })
    region?: string;

    /**
     * The list of response times based on the timeframe of the request.
     */
    @SpeakeasyMetadata({ elemType: MetricsResponseTimes })
    @Expose({ name: "response_times" })
    @Type(() => MetricsResponseTimes)
    responseTimes?: MetricsResponseTimes[];

    /**
     * The average response time for different percentiles for the request in the requested timeframe.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "this_time_period" })
    @Type(() => MetricsThisTimePeriod)
    thisTimePeriod?: MetricsThisTimePeriod;

    /**
     * The timeframe that filters this request.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "timeframe" })
    timeframe?: string;
}
