/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class NewBucket extends SpeakeasyBase {
    /**
     * Name of this bucket
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    /**
     * Unique identifier for the team to create this bucket for.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "team_id" })
    teamId: string;
}
