/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Team extends SpeakeasyBase {
    /**
     * The unique identifier for this team.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    /**
     * The name of this team.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}
