/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Environment } from "./environment";
import { Schedule } from "./schedule";
import { Expose, Type } from "class-transformer";

export class TestDetailCreatedBy extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}

export class TestDetailLastRun extends SpeakeasyBase {}

export class Steps extends SpeakeasyBase {}

export class TestDetail extends SpeakeasyBase {
    /**
     * The date the test was created in seconds (Unix time stamp format).
     */
    @SpeakeasyMetadata()
    @Expose({ name: "created_at" })
    createdAt?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "created_by" })
    @Type(() => TestDetailCreatedBy)
    createdBy?: TestDetailCreatedBy;

    @SpeakeasyMetadata()
    @Expose({ name: "default_environment_id" })
    defaultEnvironmentId?: string;

    /**
     * The description for the test.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "environments" })
    @Type(() => Environment)
    environments?: Environment;

    @SpeakeasyMetadata()
    @Expose({ name: "exported_at" })
    exportedAt?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "last_run" })
    @Type(() => TestDetailLastRun)
    lastRun?: TestDetailLastRun;

    /**
     * The name for the test.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata({ elemType: Schedule })
    @Expose({ name: "schedules" })
    @Type(() => Schedule)
    schedules?: Schedule[];

    @SpeakeasyMetadata({ elemType: Steps })
    @Expose({ name: "steps" })
    @Type(() => Steps)
    steps?: Steps[];

    @SpeakeasyMetadata()
    @Expose({ name: "trigger_url" })
    triggerUrl?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}
