/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../../../sdk/models/shared";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class GetBucketsBucketKeyTestsTestIdEnvironmentsSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=oauth2;name=Authorization" })
    runscopeAuth: string;
}

export class GetBucketsBucketKeyTestsTestIdEnvironmentsRequest extends SpeakeasyBase {
    /**
     * Unique identifier for a bucket
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=bucketKey" })
    bucketKey: string;

    /**
     * Unique identifier for a test
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=testId" })
    testId: string;
}

/**
 * List of environments belonging to this test.
 */
export class GetBucketsBucketKeyTestsTestIdEnvironmentsResponseBody extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: shared.Environment })
    @Expose({ name: "data" })
    @Type(() => shared.Environment)
    data?: shared.Environment[];

    @SpeakeasyMetadata()
    @Expose({ name: "meta" })
    @Type(() => shared.Meta)
    meta?: shared.Meta;
}

export class GetBucketsBucketKeyTestsTestIdEnvironmentsResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * List of environments belonging to this test.
     */
    @SpeakeasyMetadata()
    object?: GetBucketsBucketKeyTestsTestIdEnvironmentsResponseBody;
}
